// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RoomWithAView.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rooms.Data.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalPayment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9792f414-7cd9-42dd-9677-8f5b17de9b8d"),
                            CheckIn = new DateTime(2023, 3, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2023, 3, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("03255768-996d-4dde-9dd4-567b70d08b53"),
                            TotalPayment = 3500
                        },
                        new
                        {
                            Id = new Guid("33e38cea-1c86-4cce-999e-5316b6b4b5b4"),
                            CheckIn = new DateTime(2023, 3, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2023, 3, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("bf55a8e3-6b4a-4c57-942d-ea3e904043e0"),
                            TotalPayment = 1600
                        },
                        new
                        {
                            Id = new Guid("732b6742-f003-4148-a742-db5c4b90e086"),
                            CheckIn = new DateTime(2023, 3, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2023, 3, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("4246f3a8-afa9-492c-8048-b17c244b8c12"),
                            TotalPayment = 1200
                        });
                });

            modelBuilder.Entity("Rooms.Data.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03255768-996d-4dde-9dd4-567b70d08b53"),
                            Capacity = 5,
                            Category = "Suite",
                            Description = "Beautiful relaxing place for your tired feet",
                            Facilities = "Wi-Fi, TV, Air conditioner, Mini playground",
                            Number = 100,
                            Price = 500
                        },
                        new
                        {
                            Id = new Guid("c0a4c4a4-d7c2-43d3-b024-05fa6e32e0d9"),
                            Capacity = 1,
                            Category = "Single",
                            Description = "A perfect recharging space",
                            Facilities = "Wi-Fi, TV, Air conditioner, Mini bar",
                            Number = 101,
                            Price = 200
                        },
                        new
                        {
                            Id = new Guid("bf55a8e3-6b4a-4c57-942d-ea3e904043e0"),
                            Capacity = 2,
                            Category = "Double",
                            Description = "Let yourself be spoiled by the comfort",
                            Facilities = "Wi-Fi, TV, Air conditioner, Bath tub",
                            Number = 102,
                            Price = 400
                        },
                        new
                        {
                            Id = new Guid("1d1079a7-fa2d-4b9c-baac-843ada9e6df5"),
                            Capacity = 2,
                            Category = "Double",
                            Description = "Let yourself be spoiled by the comfort",
                            Facilities = "Wi-Fi, TV, Air conditioner, Bath tub",
                            Number = 200,
                            Price = 400
                        },
                        new
                        {
                            Id = new Guid("4246f3a8-afa9-492c-8048-b17c244b8c12"),
                            Capacity = 4,
                            Category = "Deluxe",
                            Description = "Enter the oasis of a calm and peaceful stay",
                            Facilities = "Wi-Fi, TV, Air conditioner, Bath tub,Mini bar, Daily snacks, Ocean view",
                            Number = 201,
                            Price = 600
                        });
                });

            modelBuilder.Entity("Rooms.Data.Entities.Reservation", b =>
                {
                    b.HasOne("Rooms.Data.Entities.Room", null)
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rooms.Data.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
